pairs = {
    ";": "SEMICOLON",
    "{": "CURLY_LEFT",
    "}": "CURLY_RIGHT",
    "(": "PARANT_LEFT",
    ")": "PARANT_RIGHT",
    "=": "EQUALS",
    "+": "PLUS",
    "-": "MINUS",
    "/": "SLASH",
    "*": "STAR",
    "değişken": "VAR_DECLERATION",
    "fonksiyon": "FUNC_DECLERATION",
    "eğer": "IF",
    "değilse": "ELSE",
    "değilseve": "ELIF",
}
